### ISSUE TITLE
clean() too many aruments

### ISSUE THREAD

**Issue by adammerkley** [clinton-hall/nzbToMedia#1507]
Running on Master, getting these errors now:

Traceback (most recent call last):
  File "nzbToMedia.py", line 627, in <module>
    cleanup.clean('core', 'libs')
TypeError: clean() takes exactly 1 argument (2 given)

**Comment by labrys** [comment]
@adammerkley Hotfix incomming

**Comment by adammerkley** [comment]
Cool.  Anything I should do or will a git pull from master suffice when the hot fix is ready?

**Comment by labrys** [comment]
Git pull will fix it... just missed a file during commit on previous hotfix

**Comment by labrys** [comment]
Fixed in master

**Comment by adammerkley** [comment]
Hmmm.  Still getting this after pulling from master.  Master shows up to date and .bumpversion shows version is 12.0.4.

**Comment by kcwebby** [comment]
Yep, looking at the files, nzbToMedia.py was not updated in the last commit.

cleanup.clean('core', 'libs')
It's making barfing noises over here from nzbget
Sat Jan 05 2019 23:23:18 | nzbToMedia: TypeError: clean() takes exactly 1 argument (2 given)
-- | --
INFO | Sat Jan 05 2019 23:23:18 | nzbToMedia: cleanup.clean('core', 'libs')
INFO | Sat Jan 05 2019 23:23:18 | nzbToMedia: File "/usr/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 627, in <module>

Thanks, wanted to check before posting a new issue.

**Comment by labrys** [comment]
Sorry ... don't code when tired, lol.   Fix incoming.

**Comment by labrys** [comment]
Should be fixed now in v12.0.5... I'll leave this open until confirmed.

**Comment by kcwebby** [comment]
Looks fixed to me.   I had manually coded the change, there needs to be an easier way to force git to overwrite a locally changed file...  

Thanks!
