### ISSUE TITLE
nzbToSickBeard no such file or directory - QNAP

### ISSUE THREAD

**Issue by Freakadude** [clinton-hall/nzbToMedia#1850]
**Describe the bug**
Installed Nzbget, Sickchill, Nzbtomedia all from sherpa on QNAP. Everything works fine except that nzbtomedia script runs always runs into an error as shown below even though its configured correctly within nzbget.

The script has never run successfully since install.

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'QNAP NAS'
2. Python version '3.9.6'
3. Download Client (NZBget, SABnbzd, Transmission) 'NZBGet'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'Sickchill'

**Log**
<html>
<body>

ERROR | Wed Sep 29 2021 00:45:25 | Post-process-script nzbToSiCKRAGE.py for The.Great.British.Bake.Off.S12E02.1080p.HDTV.H264-DARKFLiX failed (terminated with unknown status)
-- | -- | --
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: FileNotFoundError: [Errno 2] No such file or directory
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: self.original_directory = os.getcwd() if original is None else original
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/cleanup.py", line 38, in __init__
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: with WorkingDirectory(module_path()) as cwd:
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/cleanup.py", line 178, in clean
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: cleanup.clean(cleanup.FOLDER_STRUCTURE)
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToMedia.py", line 728, in <module>
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: import nzbToMedia
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: File "/share/Download/nzbToMedia/nzbToSiCKRAGE.py", line 273, in <module>
INFO | Wed Sep 29 2021 00:45:24 | nzbToSiCKRAGE: Traceback (most recent call last):
INFO | Wed Sep 29 2021 00:45:24 | Executing post-process-script nzbToSiCKRAGE.py for The.Great.British.Bake.Off.S12E02.1080p.HDTV.H264-DARKFLiX
INFO | Wed Sep 29 2021 00:45:24 | Post-process-script Logger.py for The.Great.British.Bake.Off.S12E02.1080p.HDTV.H264-DARKFLiX successful
INFO | Wed Sep 29 2021 00:45:24 | Executing post-process-script Logger.py for The.Great.British.Bake.Off.S12E02.1080p.HDTV.H264-DARKFLiX

</body>
</html>

**Comment by clinton-hall** [comment]
#1847 
Another user reported the same. That error was resolved by either restarting NZBGet or restarting the NAS.

**Comment by Freakadude** [comment]
Yeah i have restarted NAS and NzbGet sever times since i installed the script and it does not resolve the issue for me.

**Comment by clinton-hall** [comment]
ok... there is the issue, you are using SickChill, not SiCKRAGE. These are 2 very different forks now. So you need to be calling nzbToSickBeard.py not nzbToSiCKRAGE.py

To avoid the duplicate category name, in NZBGet, under nzbToSiCKRAGE change the category to something different... i.e. change srCategory = Sickrage to something different. You may also need to edit autoProcessMedia.cfg to disable this category.
```
[SiCKRAGE]
    [[Sickrage]] 
        enabled = 0
```

or, better yet, Change SickChill to send the download to NZBGet as a different category different e.g. `SickChill` (not Sickrage)
then set this category to call the postprocessing to nzbToSickBeard and in NZBGet, nzbToSickBeard set the `sbCategory=SickChill`

I hope this makes sense. It looks like the key issues here were:

1. Original order of scripts was causing a folder to be removed before processing <-- now solved
2. Using the incorrect (SiCKRAGE) script for your specific (SickChill) setup <-- now solved
3. Both scripts having set the same category (Sickrage) and therefore not being able to determine which process to run

**Comment by Freakadude** [comment]
Don't know which exact step was the key but i did all of them and now post processing completed successfully! So thank you for your help!

**Comment by clinton-hall** [comment]
No worries. Glad it is now working.

Sorry you had a hard time with it... the numerous combinations relating to the different SickBeard forks can make this complicated... certainly the fact that SickRage becae SickChill, and SickRageTV became SickRage, with them having very different configs now, makes this super confusing!
