### ISSUE TITLE
Files not deleted/cleaned up after processing. Missing parameter?

### ISSUE THREAD

**Issue by thesatman** [clinton-hall/nzbToMedia#721]
I have 4 scenarios:

- SickRage using torrents
- SickRage using SABnzbd
- CouchPotato using torrents
- CouchPotato using SABnzbd

Let's start with the first scenario (SickRage -> torrent), here is what is happing in the process:

1- The file is loaded in uTorrent, and download begins. = OK
2- torrentToMedia is launched after the download is 100%. = OK
3- the file is deleted from the uTorrent-list. = OK
4- Moved from c:\w_torrent_download\SickRagetv_ to c:\video\processed\SickRagetv_ = OK
5- NOT moved to Plex folder = NOT OK
6- I have to do a do manual TVrage>postprocessing = NOT OK
7- I have to do manual remove folders from c:\video\processed\SickRagetv_ = NOT OK

My setting:

[SickBeard]
    [[SickRagetv_]]
        enabled = 1
        host = localhost
        port = 8083
        username = ""
        password = ""
        Torrent_NoLink = 0
        extract = 1
        remote_path = 1
        watch_dir = C:\Video\link_w_torrent_download\SickRagetv_
        web_root = ""

[Torrent]
    clientAgent = utorrent
    useLink = hard
    outputDirectory = C:\Video\processed\
    default_downloadDirectory = W:\torrent_download
    categories = iso
    noFlatten = ""
    uTorrentWEBui = http://localhost:8082/gui/
    uTorrentUSR = <<USR>>
    uTorrentPWD = <<PWD>>

    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 1

[Extensions]
    compressedExtensions = .zip, .rar, .7z, .gz, .bz, .tar, .arj, .1, .01, .001
    mediaExtensions = .mkv, .avi, .divx, .xvid, .mov, .wmv, .mp4, .mpg, .mpeg, .vob, .iso, .m4v, .bin
    audioExtensions = .mp3, .aac, .ogg, .ape, .m4a, .asf, .wma, .flac
    metaExtensions = .nfo, .sub, .srt, .jpg, .gif

[Transcoder]
    transcode = 1
    duplicate = 1
    concat = 1
    ignoreExtensions = .avi, .mkv, .mp4
    outputFastStart = 0
    outputQualityPercent = 0
    outputVideoPath = W:\torrent_download\transcoded
    processOutput = 1

I am running nzbToMedia Version:d3adf45eb8dcaceb118b30c17b924043e3e5166b Branch:nightly (Windows 7).

What am I doing wrong?

**Comment by clinton-hall** [comment]
can you show the nzbtomedia.log?

It looks like you are either not using user/pass for sickrage, or have not set this in autoProcessMedia.cfg...
what happesn if you set user and pass?

**Comment by forkless** [comment]
I was looking in my SABnzbd completed folders and I noticed that it stopped cleaning up folders coming from SickRage right around the time last week when I decided to only make SickRage accessible from inside my LAN, so I removed the username and password authentication. I added them again, but it will have wait till later tonight until I get a new download because the post-processing does not do the last part due to 'already processed' this file, I presume you keep a database of sorts?

Anyway will know in 2-3 hours. Will keep you posted.

**Comment by clinton-hall** [comment]
It does keep a database, but it does not flag as already processed. Currently only used to aid with manual processing if auto processing failed.

Any 'already processed' messages are likely comming from SickRage.

**Comment by thesatman** [comment]
I do not use user and pwd in SR. Never have. Here is what is logged from the SR->uTorrent transaction: (You see I use TorrentToMEdia.py. OK or not OK?? )

#########################################################
2015-03-01 05:13:29 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
2015-03-01 05:13:29 INFO    ::MAIN: #########################################################
2015-03-01 05:13:29 DEBUG   ::MAIN: Options passed into TorrentToMedia: ['C:\\nzbToMedia-GIT\\nzbToMedia\\TorrentToMedia.py', 'C:\\Video\\link_w_torrent_download\\SickRagetv_\\Some_TV_Show', 'Some_TV_Show', 'SickRagetv_', 'F8DE960BECD6B14EBA446ABBEA83CA975FCD8951']
2015-03-01 05:13:29 DEBUG   ::MAIN: Adding TORRENT download info for directory C:\Video\link_w_torrent_download\SickRagetv_\Some_TV_Show to database
2015-03-01 05:13:30 DEBUG   ::MAIN: Received Directory: C:\Video\link_w_torrent_download\SickRagetv_\Some_TV_Show | Name: Some_TV_Show | Category: SickRagetv_
2015-03-01 05:13:30 DEBUG   ::MAIN: SEARCH: Found the Category: SickRagetv_ in directory structure
2015-03-01 05:13:30 INFO    ::MAIN: SEARCH: Found a unique directory Some_TV_Show in the category directory
2015-03-01 05:13:30 DEBUG   ::MAIN: Determined Directory: C:\Video\link_w_torrent_download\SickRagetv_\Some_TV_Show | Name: Some_TV_Show | Category: SickRagetv_
2015-03-01 05:13:30 INFO    ::MAIN: Auto-detected SECTION:SickBeard
2015-03-01 05:13:30 DEBUG   ::MAIN: Stopping torrent Some_TV_Show in utorrent while processing
2015-03-01 05:13:35 INFO    ::MAIN: Output directory set to: C:\Video\processed\SickRagetv_\Some_TV_Show
2015-03-01 05:13:35 DEBUG   ::MAIN: Scanning files in directory: C:\Video\link_w_torrent_download\SickRagetv_\Some_TV_Show
2015-03-01 05:13:36 DEBUG   ::MAIN: Found 2 files in C:\Video\link_w_torrent_download\SickRagetv_\Some_TV_Show
2015-03-01 05:13:36 INFO    ::COPYLINK: MEDIAFILE: [Some_TV_Show.mp4]
2015-03-01 05:13:36 INFO    ::COPYLINK: SOURCE FOLDER: [C:\Video\link_w_torrent_download\SickRagetv_\Some_TV_Show]
2015-03-01 05:13:36 INFO    ::COPYLINK: TARGET FOLDER: [C:\Video\processed\SickRagetv_\Some_TV_Show]
2015-03-01 05:13:36 INFO    ::COPYLINK: Hard linking SOURCE MEDIAFILE -> TARGET FOLDER
2015-03-01 05:13:36 WARNING ::COPYLINK: Error: The system cannot move the file to a different disk drive.
, copying instead ... 
2015-03-01 05:13:36 INFO    ::COPYLINK: Copying SOURCE MEDIAFILE -> TARGET FOLDER
2015-03-01 05:14:32 DEBUG   ::MAIN: Read only mode on file C:\Video\processed\SickRagetv_\Some_TV_Show\Some_TV_Show.mp4 Will try to make it writeable
2015-03-01 05:14:32 INFO    ::COPYLINK: MEDIAFILE: [Some_TV_Show.nfo]
2015-03-01 05:14:32 INFO    ::COPYLINK: SOURCE FOLDER: [C:\Video\link_w_torrent_download\SickRagetv_\Some_TV_Show]
2015-03-01 05:14:32 INFO    ::COPYLINK: TARGET FOLDER: [C:\Video\processed\SickRagetv_\Some_TV_Show]
2015-03-01 05:14:32 INFO    ::COPYLINK: Hard linking SOURCE MEDIAFILE -> TARGET FOLDER
2015-03-01 05:14:33 WARNING ::COPYLINK: Error: The system cannot move the file to a different disk drive.
, copying instead ... 
2015-03-01 05:14:33 INFO    ::COPYLINK: Copying SOURCE MEDIAFILE -> TARGET FOLDER
2015-03-01 05:14:33 DEBUG   ::MAIN: Read only mode on file C:\Video\processed\SickRagetv_\Some_TV_Show\Some_TV_Show.nfo Will try to make it writeable
2015-03-01 05:14:33 DEBUG   ::MAIN: Checking for archives to extract in directory: C:\Video\processed\SickRagetv_\Some_TV_Show
2015-03-01 05:14:33 INFO    ::MAIN: FLATTEN: Flattening directory: C:\Video\processed\SickRagetv_\Some_TV_Show
2015-03-01 05:14:34 DEBUG   ::MAIN: Checking for empty folders in:C:\Video\processed\SickRagetv_\Some_TV_Show
2015-03-01 05:14:34 INFO    ::MAIN: Found 1 media files in C:\Video\processed\SickRagetv_\Some_TV_Show
2015-03-01 05:14:34 INFO    ::MAIN: Calling SickBeard:SickRagetv_ to post-process:Some_TV_Show
2015-03-01 05:15:26 INFO    ::MAIN: Attempting to auto-detect SickRagetv_ fork
2015-03-01 05:15:27 INFO    ::MAIN: SickBeard:SickRagetv_ fork auto-detection successful ...
2015-03-01 05:15:27 INFO    ::MAIN: SickBeard:SickRagetv_ fork set to sickrage
2015-03-01 05:15:27 DEBUG   ::MAIN: calling command: C:\ffmpeg-20140901-git-97b8809-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error C:\nzbToMedia-GIT\nzbToMedia\tests\test.mp4
2015-03-01 05:15:29 INFO    ::TRANSCODER: Checking [Some_TV_Show.mp4] for corruption, please stand by ...
2015-03-01 05:15:29 DEBUG   ::MAIN: calling command: C:\ffmpeg-20140901-git-97b8809-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error C:\Video\processed\SickRagetv_\Some_TV_Show\Some_TV_Show.mp4
2015-03-01 05:15:30 INFO    ::TRANSCODER: SUCCESS: [Some_TV_Show.mp4] has no corruption.
2015-03-01 05:15:30 INFO    ::MAIN: Checking for files to be transcoded
2015-03-01 05:15:30 DEBUG   ::SICKBEARD: SUCCESS: Transcoding succeeded for files in C:\Video\processed\SickRagetv_\Some_TV_Show
2015-03-01 05:15:30 POSTPROCESS::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
2015-03-01 05:15:30 DEBUG   ::SICKBEARD: Opening URL: http://localhost:8083/home/postprocess/processEpisode with params: {'nzbName': 'Some_TV_Show', 'quiet': 1, 'failed': 0, 'dir': 'W:\\torrent_download\\transcoded'}
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: Processing folder W:\torrent_download\transcoded
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: TV_DOWNLOAD_DIR: 
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: PostProcessing Path: W:\torrent_download
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: PostProcessing Dirs: [u'transcoded']
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: PostProcessing Files: []
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: PostProcessing VideoFiles: []
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: PostProcessing RarContent: []
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: PostProcessing VideoInRar: []
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: Processing folder transcoded
2015-03-01 05:15:33 POSTPROCESS::SICKBEARD: Successfully processed
2015-03-01 05:15:34 DEBUG   ::MAIN: Deleting torrent Some_TV_Show from utorrent
2015-03-01 05:15:39 INFO    ::CLEANDIRS: Directory C:\Video\processed\SickRagetv_\Some_TV_Show still contains 2 unprocessed file(s), skipping ...
2015-03-01 05:15:39 INFO    ::MAIN: The C:\nzbToMedia-GIT\nzbToMedia\TorrentToMedia.py script completed successfully.

**Comment by clinton-hall** [comment]
The problem here appears to be with Transcoding. The log shows Transcoding was successful so it tells SickRage to process the transcoded directory... but no files were actually transcoded, so there are no files to process...

are you trying to transcode? if so, what bare your settings?

**Comment by thesatman** [comment]
I use this for joining cd1+cd2

[Transcoder]
    # transcode. enable to use transcoder
    transcode = 1
    ###### duplicate =1 will cretae a new file. =0 will replace the original
    duplicate = 1
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    ignoreExtensions = .avi, .mkv, .mp4

**Comment by forkless** [comment]
I can confirm that enabling authentication on SickRage caused the pp script to clean up the files again.

**Comment by clinton-hall** [comment]
I just fixed this one in nightly branch.
When you have this set of options it turns out that the output directory was created, not transcoding was needed, then an empty directory was sent to SickBeard for processing.

Now, the empty directory is removed and the original directory is processed.

**Comment by thesatman** [comment]
Did this fix include SR -> SABnzbd ? I noticed that the problem is still there. Had no torrent for the moment, but download via SABnzbd. So I shutdown SR, started it. Manually picked an episode a a TV show. The file is downloaded to the folder, but nothing is processed.

	****************************************************************************

	2015-03-22 13:41:46 DEBUG   ::MAIN: cur_commit = 1757a353da4bddc9d2735ef6a4c3e6840a3757e0 % (newest_commit)= 1757a353da4bddc9d2735ef6a4c3e6840a3757e0, num_commits_behind = 0, num_commits_ahead = 0

	2015-03-22 13:41:46 INFO    ::MAIN: No update needed

	2015-03-22 13:41:46 INFO    ::MAIN: nzbToMedia Version:1757a353da4bddc9d2735ef6a4c3e6840a3757e0 Branch:nightly (Windows 7)

	2015-03-22 13:41:46 DEBUG   ::MAIN: Connecting to utorrent: http://localhost:8082/gui/

	2015-03-22 13:41:46 INFO    ::MAIN: #########################################################

	2015-03-22 13:41:46 INFO    ::MAIN: ## ..::[nzbToMedia.pyc]::.. ##

	2015-03-22 13:41:46 INFO    ::MAIN: #########################################################

	2015-03-22 13:41:46 DEBUG   ::MAIN: Options passed into nzbToMedia: ['C:\\nzbToMedia-GIT\\nzbToMedia\\nzbToSickBeard.py', 'W:\\sabnzbd_complete\\tv\\Some_TV_Show', 'Some_TV_Show.nzb', 'Some_TV_Show', '', 'tv', 'alt.binaries.teevee', '0']

	2015-03-22 13:41:46 INFO    ::MAIN: Script triggered from SABnzbd

	2015-03-22 13:41:46 DEBUG   ::MAIN: Searching for nzoid from SAbnzbd ...

	2015-03-22 13:41:46 DEBUG   ::MAIN: Adding NZB download info for directory W:\sabnzbd_complete\tv\Some_TV_Show to database

	2015-03-22 13:41:46 INFO    ::MAIN: Auto-detected SECTION:SickBeard

	2015-03-22 13:41:46 DEBUG   ::MAIN: Checking for archives to extract in directory: W:\sabnzbd_complete\tv\Some_TV_Show

	2015-03-22 13:41:46 INFO    ::MAIN: Calling SickBeard:tv to post-process:Some_TV_Show.nzb

	2015-03-22 13:41:47 INFO    ::MAIN: Attempting to auto-detect tv fork

	2015-03-22 13:41:49 INFO    ::MAIN: SickBeard:tv fork auto-detection successful ...

	2015-03-22 13:41:49 INFO    ::MAIN: SickBeard:tv fork set to sickrage

	2015-03-22 13:41:49 DEBUG   ::MAIN: calling command: C:\ffmpeg-20140901-git-97b8809-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error C:\nzbToMedia-GIT\nzbToMedia\tests\test.mp4

	2015-03-22 13:41:49 INFO    ::TRANSCODER: Checking [Some_TV_Show.mkv] for corruption, please stand by ...

	2015-03-22 13:41:49 DEBUG   ::MAIN: calling command: C:\ffmpeg-20140901-git-97b8809-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error W:\sabnzbd_complete\tv\Some_TV_Show\Some_TV_Show.mkv

	2015-03-22 13:41:49 INFO    ::TRANSCODER: SUCCESS: [Some_TV_Show.mkv] has no corruption.

	2015-03-22 13:41:49 INFO    ::MAIN: FLATTEN: Flattening directory: W:\sabnzbd_complete\tv\Some_TV_Show

	2015-03-22 13:41:49 DEBUG   ::MAIN: Checking for empty folders in:W:\sabnzbd_complete\tv\Some_TV_Show

	2015-03-22 13:41:49 INFO    ::MAIN: FLATTEN: Flattening directory: W:\sabnzbd_complete\tv\Some_TV_Show

	2015-03-22 13:41:49 DEBUG   ::MAIN: Checking for empty folders in:W:\sabnzbd_complete\tv\Some_TV_Show

	2015-03-22 13:41:49 INFO    ::MAIN: Checking for files to be transcoded

	 

	***************************************************************************

**Comment by clinton-hall** [comment]
it appears to now be failing at the transcode section.
Can you open a command window, paste the following command `'C:\\nzbToMedia-GIT\\nzbToMedia\\nzbToSickBeard.py' 'W:\\sabnzbd_complete\\tv\\Some_TV_Show' 'Some_TV_Show.nzb' 'Some_TV_Show' '' 'tv alt.binaries.teevee' '0'`
Then hopefully the failure will be displayed in the command prompt.

**Comment by thesatman** [comment]
C:\Users\Harry>C:\\nzbToMedia-GIT\\nzbToMedia\\nzbToSickBeard.py "W:\sabnzbd_complete\tv\Some_TV_Show" "Some_TV_Show.nzb" "Some_TV_Show"  ""  "tv"  "alt.binaries.teevee"  "0"

	 

	Resulted in :

	 

	***************************************************************

	[08:12:51] [DEBUG]::MAIN: cur_commit = 1757a353da4bddc9d2735ef6a4c3e6840a3757e0 % (newest_commit)= 1757a353da4bddc9d2735

	ef6a4c3e6840a3757e0, num_commits_behind = 0, num_commits_ahead = 0

	[08:12:51] [INFO]::MAIN: No update needed

	[08:12:51] [INFO]::MAIN: nzbToMedia Version:1757a353da4bddc9d2735ef6a4c3e6840a3757e0 Branch:nightly (Windows 7)

	[08:12:52] [DEBUG]::MAIN: Connecting to utorrent: http://localhost:8082/gui/

	[08:12:52] [INFO]::MAIN: #########################################################

	[08:12:52] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##

	[08:12:52] [INFO]::MAIN: #########################################################

	[08:12:52] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\nzbToMedia-GIT\\nzbToMedia\\nzbToSickBeard.py', 'W:\\sabnzbd_complete\\tv\\Some_TV_Show', 'Revenge.S04E17.HDTV.x264-LOL.nzb', 'Revenge S04E17 HDTV x264-LOL', '', 'tv', 'alt.binaries.teevee', '0']

	[08:12:52] [INFO]::MAIN: Script triggered from SABnzbd

	[08:12:52] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...

	[08:12:52] [DEBUG]::MAIN: Adding NZB download info for directory W:\sabnzbd_complete\tv\Some_TV_Show to database

	[08:12:53] [INFO]::MAIN: Auto-detected SECTION:SickBeard

	[08:12:53] [DEBUG]::MAIN: Checking for archives to extract in directory: W:\sabnzbd_complete\tv\Some_TV_Show

	[08:12:54] [INFO]::MAIN: Calling SickBeard:tv to post-process:Some_TV_Show.nzb

	[08:13:00] [INFO]::MAIN: Attempting to auto-detect tv fork

	[08:13:03] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...

	[08:13:03] [INFO]::MAIN: SickBeard:tv fork set to sickrage

	[08:13:03] [DEBUG]::MAIN: calling command: C:\ffmpeg-20140901-git-97b8809-win64-static\bin\ffprobe.exe -v quiet -print_f

	ormat json -show_format -show_streams -show_error C:\nzbToMedia-GIT\nzbToMedia\tests\test.mp4

	[08:13:03] [INFO]::TRANSCODER: Checking [Some_TV_Show.mp4] for corruption, please stand by ...

	[08:13:03] [DEBUG]::MAIN: calling command: C:\ffmpeg-20140901-git-97b8809-win64-static\bin\ffprobe.exe -v quiet -print_f

	ormat json -show_format -show_streams -show_error W:\sabnzbd_complete\tv\Some_TV_Show\Some_TV_Show.mp4

	[08:13:20] [INFO]::TRANSCODER: SUCCESS: [Some_TV_show.mp4] has no corruption.

	[08:13:20] [INFO]::MAIN: FLATTEN: Flattening directory: W:\sabnzbd_complete\tv\Some_TV_Show

	[08:13:20] [DEBUG]::MAIN: Checking for empty folders in:W:\sabnzbd_complete\tv\Some_TV_Show

	[08:13:20] [INFO]::MAIN: FLATTEN: Flattening directory: W:\sabnzbd_complete\tv\Some_TV_Show

	[08:13:20] [DEBUG]::MAIN: Checking for empty folders in:W:\sabnzbd_complete\tv\Some_TV_Show

	[08:13:20] [INFO]::MAIN: Checking for files to be transcoded

	Traceback (most recent call last):

	  File "C:\nzbToMedia-GIT\nzbToMedia\nzbToSickBeard.py", line 257, in <module>

	    result = nzbToMedia.main(sys.argv, section)

	  File "C:\nzbToMedia-GIT\nzbToMedia\nzbToMedia.py", line 710, in main

	    download_id='')

	  File "C:\nzbToMedia-GIT\nzbToMedia\nzbToMedia.py", line 598, in process

	    download_id, inputCategory, failureLink)

	  File "C:\nzbToMedia-GIT\nzbToMedia\nzbtomedia\autoProcess\autoProcessTV.py", line 193, in processEpisode

	    result, newDirName = transcoder.Transcode_directory(dirName)

	  File "C:\nzbToMedia-GIT\nzbToMedia\nzbtomedia\transcoder\transcoder.py", line 772, in Transcode_directory

	    newDir = dirname

	NameError: global name 'dirname' is not defined

	 

	*****************************************************************************

**Comment by clinton-hall** [comment]
Sorry about that. Stupid typo....
This should be fixed now.

**Comment by thesatman** [comment]
Thank you very much. SickRage >> SABnzbd seems to be working fine now. Cleaning up and removing empty folders. I'll have to wait for the next download with uTorrent or Couchpotato to see what will happen. If anything goes wrong, I'll let you know.

	Thank you for the fix !
